name: my_card
description: Cartão pessoal - Curso de Flutter e Dart.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  cupertino_icons: ^0.1.3
  url_launcher: ^ 5.4.1
  # flutter_icons: ^ 1.1.0
  ionicons: ^0.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - imagens/bruna2.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fontes/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fontes/SourceSansPro-Regular.ttf
    - family: GreatVibes
      fonts:
        - asset: fontes/GreatVibes-Regular.ttf
        